### ISSUE TITLE
No registered env with id: 

### ISSUE THREAD

**Issue by OfekShochat** [genyrosk/gym-chess#7]
Gym says there is no registered id with the env. in the start; I didn't know why because I didn't see any issues that talk about that. Then I tried to copy-paste your example to see, even that I knew it would not work. 
full error(it is the same):

Traceback (most recent call last):
  File "C:\Users\o\AppData\Local\Programs\Python\Python38-32\lib\site-packages\gym\envs\registration.py", line 121, in spec
    return self.env_specs[id]
KeyError: 'ChessVsSelf-v2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:/q learning chess/test.py", line 8, in <module>
    env = gym.make('ChessVsSelf-v2')
  File "C:\Users\o\AppData\Local\Programs\Python\Python38-32\lib\site-packages\gym\envs\registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "C:\Users\o\AppData\Local\Programs\Python\Python38-32\lib\site-packages\gym\envs\registration.py", line 89, in make
    spec = self.spec(path)
  File "C:\Users\o\AppData\Local\Programs\Python\Python38-32\lib\site-packages\gym\envs\registration.py", line 131, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: ChessVsSelf-v2

**Comment by ZippZopp** [comment]
i looked in the init file of the package and it looks like you should use 'Chess-v0'.
![Screenshot from 2020-11-25 22-11-12](https://user-images.githubusercontent.com/74837362/100282048-3d37b800-2f6b-11eb-88a2-d295c9827f39.png)
'

**Comment by genyrosk** [comment]
Apologies for the absence 🙏 

New version called `v1` has just been released #8, let me know if you still have the same problem and feel free to open it in a new issue, thanks !
